// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgbyypdalgxnepunqwwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnYnl5cGRhbGd4bmVwdW5xd3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODE1NjksImV4cCI6MjA2NzE1NzU2OX0.czIJ3NFgKU4AIvc_Uh4bQD3Wma-D6Jx-jmh4_rY9Ydo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});